local items = {
    {
        name='iron-plate',
        tech='automation'
    },
    {
        name='copper-plate',
        tech='automation'
    },
    {
        name='stone-brick',
        tech='automation'
    },
    {
        name='steel-plate',
        tech='steel-processing'
    },
    {
        name='basic-oil-processing',
        tech='oil-processing'
    },
    {
        name='advanced-oil-processing',
        tech='advanced-oil-processing'
    },
    {
        name='heavy-oil-cracking',
        tech='advanced-oil-processing'
    },
    {
        name='light-oil-cracking',
        tech='advanced-oil-processing'
    },
    {
        name='solid-fuel-from-light-oil',
        tech='advanced-oil-processing'
    },
    {
        name='solid-fuel-from-heavy-oil',
        tech='advanced-oil-processing'
    },
    {
        name='solid-fuel-from-petroleum-gas',
        tech='oil-processing'
    },
    {
        name='coal-liquefaction',
        tech='coal-liquefaction'
    },
    {
        name='sulfur',
        tech='sulfur-processing'
    },
    {
        name='sulfuric-acid',
        tech='sulfur-processing'
    },
    {
        name='lubricant',
        tech='lubricant'
    },
    {
        name='plastic-bar',
        tech='plastics'
    },
    {
        name='battery',
        tech='battery'
    },
    {
        name='explosives',
        tech='explosives'
    },
    {
        name='cliff-explosives',
        tech='cliff-explosives'
    },
    {
        name='empty-barrel',
        tech='fluid-handling'
    },
    {
        name='copper-cable',
        tech='automation'
    },
    {
        name='iron-stick',
        tech='automation'
    },
    {
        name='iron-gear-wheel',
        tech='automation'
    },
    {
        name='pipe',
        tech='automation'
    },
    {
        name='electronic-circuit',
        tech='automation'
    },
    {
        name='advanced-circuit',
        tech='advanced-electronics'
    },
    {
        name='processing-unit',
        tech='advanced-electronics-2'
    },
    {
        name='engine-unit',
        tech='engine'
    },
    {
        name='electric-engine-unit',
        tech='electric-engine'
    },
    {
        name='flying-robot-frame',
        tech='robotics'
    },
    {
        name='low-density-structure',
        tech='low-density-structure'
    },
    {
        name='rocket-fuel',
        tech='rocket-fuel'
    },
    {
        name='rocket-control-unit',
        tech='rocket-control-unit'
    },
    {
        name='automation-science-pack',
        tech='automation'
    },
    {
        name='logistic-science-pack',
        tech='logistic-science-pack'
    },
    {
        name='chemical-science-pack',
        tech='chemical-science-pack'
    },
    {
        name='military-science-pack',
        tech='military-science-pack'
    },
    {
        name='production-science-pack',
        tech='production-science-pack'
    },
    {
        name='utility-science-pack',
        tech='utility-science-pack'
    },
    {
        name='inserter',
        tech='automation'
    },
    {
        name='transport-belt',
        tech='automation'
    },
    {
        name='grenade',
        tech='military-2'
    },
    {
        name='firearm-magazine',
        tech='automation'
    },
    {
        name='piercing-rounds-magazine',
        tech='military-2'
    },
    {
        name='stone-wall',
        tech='stone-wall'
    },
    {
        name='rail',
        tech='railway'
    },
    {
        name='electric-furnace',
        tech='advanced-material-processing-2'
    },
    {
        name='concrete',
        tech='concrete'
    },
    {
        name='uranium-processing',
        tech='uranium-processing'
    },
    {
        name='uranium-fuel-cell',
        tech='uranium-processing'
    },
    {
        name='nuclear-fuel-reprocessing',
        tech='nuclear-fuel-reprocessing'
    },
    {
        name='kovarex-enrichment-process',
        tech='kovarex-enrichment-process'
    },
    {
        name='nuclear-fuel',
        tech='kovarex-enrichment-process'
    },
    {
        name='fast-inserter',
        tech='fast-inserter'
    },
    {
        name='filter-inserter',
        tech='fast-inserter'
    },
    {
        name='long-handed-inserter',
        tech='automation'
    },
    {
        name='stack-inserter',
        tech='stack-inserter'
    },
    {
        name='stack-filter-inserter',
        tech='stack-inserter'
    },
    {
        name='uranium-rounds-magazine',
        tech='uranium-ammo'
    },
    {
        name='explosive-cannon-shell',
        tech='tank'
    },
    {
        name='artillery-shell',
        tech='artillery'
    },
    {
        name='rocket',
        tech='rocketry'
    },
    {
        name='explosive-rocket',
        tech='explosive-rocketry'
    },
    {
        name='solar-panel',
        tech='solar-energy'
    },
    {
        name='accumulator',
        tech='electric-energy-accumulators'
    },
    {
        name='radar',
        tech='automation'
    }
}

return items